//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TomPIT.BigData.Providers.Sql {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SqlStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TomPIT.BigData.Providers.Sql.SqlStrings", typeof(SqlStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE [{0}] ADD [{1}] {2}.
        /// </summary>
        internal static string ColumnCreate {
            get {
                return ResourceManager.GetString("ColumnCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE [{0}] DROP COLUMN [{1}].
        /// </summary>
        internal static string ColumnDrop {
            get {
                return ResourceManager.GetString("ColumnDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH 
        ///	FROM  INFORMATION_SCHEMA.COLUMNS 
        ///	WHERE TABLE_NAME = &apos;{0}&apos;
        ///	and COLUMN_NAME not in(&apos;id&apos;, &apos;timestamp&apos;);.
        /// </summary>
        internal static string ColumnQuery {
            get {
                return ResourceManager.GetString("ColumnQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF NOT EXISTS(SELECT * FROM sys.indexes WHERE object_id = object_id(&apos;{0}&apos;) AND NAME =&apos;IX_{0}_{1}&apos;)
        ///  CREATE INDEX IX_{0}_{1} ON {0} ({1});.
        /// </summary>
        internal static string CreateIndex {
            get {
                return ResourceManager.GetString("CreateIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE merge_{0}
        ///	@rows struct_{0} READONLY
        ///AS
        ///
        ///MERGE {0} AS t
        ///USING (SELECT * FROM @rows) AS s ({1})
        ///ON ({2})
        ///	WHEN matched THEN
        ///		UPDATE SET {3}
        ///	WHEN not matched THEN
        ///		INSERT ({1}) values ({4})
        ///  OUTPUT $action, inserted.*;.
        /// </summary>
        internal static string CreateMergeProcedure {
            get {
                return ResourceManager.GetString("CreateMergeProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TYPE dbo.struct_{0} AS TABLE 
        ///({1}
        ///).
        /// </summary>
        internal static string CreateTableType {
            get {
                return ResourceManager.GetString("CreateTableType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE merge_{0}
        ///	@rows struct_{1} READONLY
        ///AS
        ///
        ///MERGE {1} AS t
        ///USING (SELECT * FROM @rows) AS s ({2})
        ///ON ({3})
        ///	WHEN matched THEN
        ///		UPDATE SET {4}
        ///	OUTPUT inserted.*;.
        /// </summary>
        internal static string CreateUpdateProcedure {
            get {
                return ResourceManager.GetString("CreateUpdateProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF EXISTS(SELECT * FROM sys.indexes WHERE object_id = object_id(&apos;{0}&apos;) AND NAME =&apos;IX_{0}_{1}&apos;)
        ///	DROP INDEX IX_{0}_{1} ON {0}.
        /// </summary>
        internal static string DropIndex {
            get {
                return ResourceManager.GetString("DropIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF EXISTS ( SELECT  * FROM    sys.objects WHERE   object_id = OBJECT_ID(N&apos;merge_{0}&apos;) AND type IN (N&apos;P&apos;, N&apos;PC&apos;)) 
        ///DROP PROCEDURE merge_{0}.
        /// </summary>
        internal static string DropProcedure {
            get {
                return ResourceManager.GetString("DropProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF EXISTS ( SELECT  * FROM    sys.objects WHERE   object_id = OBJECT_ID(N&apos;merge_{0}&apos;) AND type IN (N&apos;P&apos;, N&apos;PC&apos;)) 
        ///DROP PROCEDURE merge_{0}.
        /// </summary>
        internal static string DropProcedureUpdate {
            get {
                return ResourceManager.GetString("DropProcedureUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF EXISTS (SELECT * FROM sys.types WHERE is_table_type = 1 AND name = &apos;struct_{0}&apos;)
        /// DROP TYPE struct_{0}.
        /// </summary>
        internal static string DropStruct {
            get {
                return ResourceManager.GetString("DropStruct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;{0}&apos;) AND type IN (N&apos;U&apos;)) 
        ///  DROP TABLE {0}.
        /// </summary>
        internal static string DropTable {
            get {
                return ResourceManager.GetString("DropTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE [dbo].[{0}] ADD  CONSTRAINT [DF_{0}_timestamp]  DEFAULT (getutcdate()) FOR [timestamp].
        /// </summary>
        internal static string TableAddTimestampDefault {
            get {
                return ResourceManager.GetString("TableAddTimestampDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET ANSI_NULLS ON  
        ///SET QUOTED_IDENTIFIER ON 
        ///
        ///CREATE TABLE [dbo].[{0}](
        ///	[id] [int] IDENTITY(1,1) NOT NULL,
        ///	[timestamp] [datetime2] NOT NULL,
        /// CONSTRAINT [PK_{0}] PRIMARY KEY CLUSTERED 
        ///(
        ///	[id] ASC
        ///)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
        ///) ON [PRIMARY].
        /// </summary>
        internal static string TableCreate {
            get {
                return ResourceManager.GetString("TableCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select case when exists (select * from information_schema.tables where table_name = &apos;{0}&apos;) then 1 else 0 end;.
        /// </summary>
        internal static string TableExists {
            get {
                return ResourceManager.GetString("TableExists", resourceCulture);
            }
        }
    }
}
