<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <AssemblyVersion>6.1.626.15</AssemblyVersion>
    <FileVersion>6.1.626.15</FileVersion>
    <Version>6.1.626.15</Version>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Core\TomPIT.Core\TomPIT.Core.csproj" />
  </ItemGroup>
</Project>