using System;

namespace TomPIT.Storage
{
	public class BlobTypes
	{
		/*
		 * Blobs under 500 are deleted by installer
		 */
		public const int Configuration = 1;
		[Obsolete("Please use SourceText constant instead.")]
		public const int Template = 2;
		public const int SourceText = 2;

		[Obsolete]
		public const int ComponentHistory = 4;
		public const int AutoGenerated = 5;

		public const int WorkerState = 504;

		[Obsolete]
		public const int Package = 505;
		[Obsolete]
		public const int InstallerConfiguration = 506;
		public const int Avatar = 511;
		public const int HtmlImage = 521;
		public const int BigDataPartitionSchema = 531;
		//public const int Manifest = 541;
		[Obsolete]
		public const int ScriptManifest = 542;
		[Obsolete]
		public const int ScriptManifestMetaData = 543;
		/*
		 * Blobs over 1000 are not notified by backplane by default
		 */
		[Obsolete]
		public const int RuntimeConfigurationBackup = 1001;
		[Obsolete]
		public const int RuntimeConfigurationState = 1002;
		[Obsolete]
		public const int DatabaseState = 1003;
		public const int UserContent = 1103;
		public const int BigDataTransactionBlock = 1201;
		public const int MailAttachment = 1301;
	}
}
