<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <Configurations>Debug;Release;Development</Configurations>
    <AssemblyVersion>5.1.724.1</AssemblyVersion>
    <FileVersion>5.1.724.1</FileVersion>
    <Version>5.1.724.1</Version>
  </PropertyGroup>
  <PropertyGroup>
    <AppConfig>App.$(Configuration).config</AppConfig>
    <UserSecretsId>3689bad2-2146-4946-9c4a-839e2fbe53d5</UserSecretsId>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Development|AnyCPU'">
    <Optimize>false</Optimize>
    <DefineConstants>TRACE;TESTING;SIMULATION;CONSOLE</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CommandLineParser" Version="2.9.1" />
    <PackageReference Include="devexpress.aspnetcore.reporting" Version="23.1.6" />
    <PackageReference Include="DevExpress.CrossPlatform.Printing.DrawingEngine" Version="1.0.14" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Systemd" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="9.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.Drawing.Common" Version="9.0.0" />
    <PackageReference Include="System.Text.Encodings.Web" Version="9.0.0" />
  </ItemGroup>
</Project>