<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <AssemblyVersion>6.1.608.4</AssemblyVersion>
    <FileVersion>6.1.608.4</FileVersion>
    <Version>6.1.608.4</Version>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Connected.SaaS.Clients\Connected.SaaS.Clients.csproj" />
  </ItemGroup>
</Project>