<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <AssemblyVersion>6.1.408.1</AssemblyVersion>
    <FileVersion>6.1.408.1</FileVersion>
    <Version>6.1.408.1</Version>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Core\TomPIT.Sdk\TomPIT.Sdk.csproj" />
  </ItemGroup>
</Project>