<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyVersion>6.1.406.4</AssemblyVersion>
    <FileVersion>6.1.406.4</FileVersion>
    <Version>6.1.406.4</Version>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.1.2" />
    <PackageReference Include="microsoft.extensions.logging" Version="7.0.0" />
    <PackageReference Include="Microsoft.SqlServer.SqlManagementObjects" Version="170.18.0" />
  </ItemGroup>
</Project>