<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <RootNamespace>TomPIT.Mcp</RootNamespace>
    <AssemblyVersion>6.2.713.19</AssemblyVersion>
    <FileVersion>6.2.713.19</FileVersion>
    <Version>6.2.713.19</Version>
    <Authors>Tom PIT</Authors>
    <Company>Tom PIT</Company>
    <Product>Tom PIT.connected</Product>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.8.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Core\TomPIT.ComponentModel\TomPIT.ComponentModel.csproj" />
    <ProjectReference Include="..\..\Core\TomPIT.Core\TomPIT.Core.csproj" />
    <ProjectReference Include="..\..\Core\TomPIT.Sdk\TomPIT.Sdk.csproj" />
    <ProjectReference Include="..\..\Runtime\TomPIT.Runtime\TomPIT.Runtime.csproj" />
  </ItemGroup>
</Project>
