<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <AssemblyVersion>6.2.701.18</AssemblyVersion>
    <FileVersion>6.2.701.18</FileVersion>
    <Version>6.2.701.18</Version>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Core\TomPIT.Sdk\TomPIT.Sdk.csproj" />
    <ProjectReference Include="..\Sys\TomPIT.Sys\Sys.csproj" />
  </ItemGroup>
</Project>