//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TomPIT {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SRM {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SRM() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TomPIT.SRM", typeof(SRM).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string WorkerDay {
            get {
                return ResourceManager.GetString("WorkerDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string WorkerDayDay {
            get {
                return ResourceManager.GetString("WorkerDayDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        public static string WorkerDayDays {
            get {
                return ResourceManager.GetString("WorkerDayDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every.
        /// </summary>
        public static string WorkerDayEvery {
            get {
                return ResourceManager.GetString("WorkerDayEvery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        public static string WorkerDayFriday {
            get {
                return ResourceManager.GetString("WorkerDayFriday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        public static string WorkerDayMonday {
            get {
                return ResourceManager.GetString("WorkerDayMonday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        public static string WorkerDaySaturday {
            get {
                return ResourceManager.GetString("WorkerDaySaturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        public static string WorkerDaySunday {
            get {
                return ResourceManager.GetString("WorkerDaySunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        public static string WorkerDayThursday {
            get {
                return ResourceManager.GetString("WorkerDayThursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        public static string WorkerDayTuesday {
            get {
                return ResourceManager.GetString("WorkerDayTuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        public static string WorkerDayWednesday {
            get {
                return ResourceManager.GetString("WorkerDayWednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekday.
        /// </summary>
        public static string WorkerDayWeekday {
            get {
                return ResourceManager.GetString("WorkerDayWeekday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekend.
        /// </summary>
        public static string WorkerDayWeekend {
            get {
                return ResourceManager.GetString("WorkerDayWeekend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workdays.
        /// </summary>
        public static string WorkerDayWorkdays {
            get {
                return ResourceManager.GetString("WorkerDayWorkdays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        public static string WorkerDisable {
            get {
                return ResourceManager.GetString("WorkerDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ms.
        /// </summary>
        public static string WorkerElapsedMs {
            get {
                return ResourceManager.GetString("WorkerElapsedMs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string WorkerEnable {
            get {
                return ResourceManager.GetString("WorkerEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End after.
        /// </summary>
        public static string WorkerEndAfter {
            get {
                return ResourceManager.GetString("WorkerEndAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End by.
        /// </summary>
        public static string WorkerEndBy {
            get {
                return ResourceManager.GetString("WorkerEndBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End time.
        /// </summary>
        public static string WorkerEndTime {
            get {
                return ResourceManager.GetString("WorkerEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution range.
        /// </summary>
        public static string WorkerExecutionRange {
            get {
                return ResourceManager.GetString("WorkerExecutionRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to faults.
        /// </summary>
        public static string WorkerFaults {
            get {
                return ResourceManager.GetString("WorkerFaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour.
        /// </summary>
        public static string WorkerHour {
            get {
                return ResourceManager.GetString("WorkerHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run worker every number of hours.
        /// </summary>
        public static string WorkerHourCount {
            get {
                return ResourceManager.GetString("WorkerHourCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last run.
        /// </summary>
        public static string WorkerLastRun {
            get {
                return ResourceManager.GetString("WorkerLastRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute.
        /// </summary>
        public static string WorkerMinute {
            get {
                return ResourceManager.GetString("WorkerMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run worker every number of minutes.
        /// </summary>
        public static string WorkerMinuteCount {
            get {
                return ResourceManager.GetString("WorkerMinuteCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string WorkerMonth {
            get {
                return ResourceManager.GetString("WorkerMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to April.
        /// </summary>
        public static string WorkerMonthApril {
            get {
                return ResourceManager.GetString("WorkerMonthApril", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to August.
        /// </summary>
        public static string WorkerMonthAugust {
            get {
                return ResourceManager.GetString("WorkerMonthAugust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string WorkerMonthDay {
            get {
                return ResourceManager.GetString("WorkerMonthDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to December.
        /// </summary>
        public static string WorkerMonthDecember {
            get {
                return ResourceManager.GetString("WorkerMonthDecember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of every.
        /// </summary>
        public static string WorkerMonthEvery {
            get {
                return ResourceManager.GetString("WorkerMonthEvery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to February.
        /// </summary>
        public static string WorkerMonthFebruary {
            get {
                return ResourceManager.GetString("WorkerMonthFebruary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        public static string WorkerMonthFirst {
            get {
                return ResourceManager.GetString("WorkerMonthFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fourth.
        /// </summary>
        public static string WorkerMonthFourth {
            get {
                return ResourceManager.GetString("WorkerMonthFourth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to January.
        /// </summary>
        public static string WorkerMonthJanuary {
            get {
                return ResourceManager.GetString("WorkerMonthJanuary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to July.
        /// </summary>
        public static string WorkerMonthJuly {
            get {
                return ResourceManager.GetString("WorkerMonthJuly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to June.
        /// </summary>
        public static string WorkerMonthJune {
            get {
                return ResourceManager.GetString("WorkerMonthJune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        public static string WorkerMonthLast {
            get {
                return ResourceManager.GetString("WorkerMonthLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to March.
        /// </summary>
        public static string WorkerMonthMarch {
            get {
                return ResourceManager.GetString("WorkerMonthMarch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May.
        /// </summary>
        public static string WorkerMonthMay {
            get {
                return ResourceManager.GetString("WorkerMonthMay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to months.
        /// </summary>
        public static string WorkerMonthMonths {
            get {
                return ResourceManager.GetString("WorkerMonthMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to November.
        /// </summary>
        public static string WorkerMonthNovember {
            get {
                return ResourceManager.GetString("WorkerMonthNovember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to October.
        /// </summary>
        public static string WorkerMonthOctober {
            get {
                return ResourceManager.GetString("WorkerMonthOctober", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second.
        /// </summary>
        public static string WorkerMonthSecond {
            get {
                return ResourceManager.GetString("WorkerMonthSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to September.
        /// </summary>
        public static string WorkerMonthSeptember {
            get {
                return ResourceManager.GetString("WorkerMonthSeptember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The.
        /// </summary>
        public static string WorkerMonthThe {
            get {
                return ResourceManager.GetString("WorkerMonthThe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third.
        /// </summary>
        public static string WorkerMonthThird {
            get {
                return ResourceManager.GetString("WorkerMonthThird", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to next run.
        /// </summary>
        public static string WorkerNextRun {
            get {
                return ResourceManager.GetString("WorkerNextRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No end date.
        /// </summary>
        public static string WorkerNoEnd {
            get {
                return ResourceManager.GetString("WorkerNoEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to occurences.
        /// </summary>
        public static string WorkerOccurences {
            get {
                return ResourceManager.GetString("WorkerOccurences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once.
        /// </summary>
        public static string WorkerOnce {
            get {
                return ResourceManager.GetString("WorkerOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution pattern.
        /// </summary>
        public static string WorkerPattern {
            get {
                return ResourceManager.GetString("WorkerPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queued.
        /// </summary>
        public static string WorkerQueued {
            get {
                return ResourceManager.GetString("WorkerQueued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string WorkerReset {
            get {
                return ResourceManager.GetString("WorkerReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        public static string WorkerRun {
            get {
                return ResourceManager.GetString("WorkerRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second.
        /// </summary>
        public static string WorkerSecond {
            get {
                return ResourceManager.GetString("WorkerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run worker every number of seconds.
        /// </summary>
        public static string WorkerSecondCount {
            get {
                return ResourceManager.GetString("WorkerSecondCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        public static string WorkerStartDate {
            get {
                return ResourceManager.GetString("WorkerStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time.
        /// </summary>
        public static string WorkerStartTime {
            get {
                return ResourceManager.GetString("WorkerStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        public static string WorkerWeek {
            get {
                return ResourceManager.GetString("WorkerWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run worker every number of weeks.
        /// </summary>
        public static string WorkerWeekCount {
            get {
                return ResourceManager.GetString("WorkerWeekCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working hours.
        /// </summary>
        public static string WorkerWorkingHours {
            get {
                return ResourceManager.GetString("WorkerWorkingHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string WorkerYear {
            get {
                return ResourceManager.GetString("WorkerYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run worker every number of years.
        /// </summary>
        public static string WorkerYearCount {
            get {
                return ResourceManager.GetString("WorkerYearCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from.
        /// </summary>
        public static string WorkerYearFrom {
            get {
                return ResourceManager.GetString("WorkerYearFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string WorkerYearOn {
            get {
                return ResourceManager.GetString("WorkerYearOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On the.
        /// </summary>
        public static string WorkerYearOnThe {
            get {
                return ResourceManager.GetString("WorkerYearOnThe", resourceCulture);
            }
        }
    }
}
